vich_uploader:
    db_driver: orm

    mappings:
       service:
           uri_prefix: /images/service
           upload_destination: '%kernel.project_dir%/public/images/service'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
